apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-secret
  namespace: default
spec:
  encryptedData:
    password: AgAs8nun6JQfba39jZGDDDY5WH4NFzngjcTBmP6t6QCxYLEQUW/HwMk4la2wULrVP28sl7H+QDubVSJ4qkUPGqmoac0SsavzMnJY5j6B4Of+kOSzhXpREHWrW6CJH+VQczRlQDF0Xl4E2NcrUJfMQdJH7/J7gXPKjVUgXdJ6UEiwJscCNuajH1FMIFNuSSK6eQd8Vo3OKb5GiS21mtac74cNbd+yBL7umbO/K5bRq4dSQWwHIIsZmXjafJ1SIT0rxIiGJ5i8AKBrPihlAcW4m8PGGRcnS0g8PxhGbQoCzG1GQKvC9ktI27ARiIBtZwQSBJmyj7n1tiaYboAYHYQesxgzbSDLnFH2RMcZNjsLR5e/LpylDz/feHCi3p8EDHGXvODQkk98rhnIT7qtaF8uPfVZ9DgnZdoetpaL/m6w6ADnEdG3mjNTgJZ7knmJj0jkSxMVT13ZV4kso+6TW3m9XnPIB/n06OANb4iDeqqRwu+oQPDW58AGWvrbx9tZ1gO+HYzLIkWyQMQ8In82YxTSPFb9PvkVSxuU/b+3miVPxWk5Md6huglV7Q+dbvxBwmTsFLPPfEz1EEAD0YcmzguluidEF6U6UJ1leU38upsGoTfEVY6WXyUaUUmV17y+z8dAKcUtsU/RAtX9YWz0TMTtxFIlaeLIeal1QhlRpKcUy7SbMs972UcB/aSQj49ugJ7rih69POviJOShX/P2gSdRuKwRn4XrkBY=
    username: AgBwPwXIdfu+Pkd0H7vAFwYFP9FuF2BQT2DXa0B9JQ8ZB9PtKSmHWmhlHwqzYwURq0nvf8vxeelGQtVggzP+feGj52JmkVqK/H/kcaoD7jAZ2O3zHhVelcpZxFeahojql4lfpTRjAIXLp4mxB3Q7+zwr8Myi0uP8ddIrxu1aeLI+T+L5B5TLOOwd+9eOHy2Ogd6TvQ+gwVbLzWLnwy9Z0S/9gFKDItrx8ngK1+F0rJf+2Vf34UxgJ1DITeC8SNxLSJ29DodE8xJzrCkd7Lig05wSDSyIZB5+vPzOvI4bYDa6zO6ZSkftjlQQ6+EGHNdZDl928lrCc28CiUtNUhSCKy9uvHAgV/fYGw27mPZM6LEex87HiuWKelDHrvRKoeaB82Hw6DFo0Bt4OTWBj7wFq997zOM4RlmXTbFVmmLdC9AFMobiYTRZeSBKoLPp6IRMmuIs/VeDrcmml9XKfxNc6vGBS4AePdE4aNOCQMSMBxMxifCey/JhBlPyjg9ci2Mw3Zxp3eHTVlwF2v4fDWI60vLEv9nvZfAaebIg0OagVPsxp2yWUM0Z4jRKddC7c7YvodHuAqZJzxNyrNAiPm83Cajv7ifJ/bZ6AfxT3Yqt4RMn5K+tFTjs32GUu6csLh7GU7J5CvqGQQHPhfnDZFDceYhEqX93q6JQEMXqfH06A+Ql2VEUVJ+mCbIid69Oz708RufZPcA6UQ==
  template:
    metadata:
      creationTimestamp: null
      name: database-secret
      namespace: default
---
